Repository shriproperty/client, pull requests merged in 2022-09, with the labels that each got.

#105 feat::sparkles: setup ant design and tailwind
  .vscode/settings.json
  craco.config.js
  package.json
  postcss.config.js
  src/.eslintrc
  src/App.tsx
  src/app.css
  src/app.less
  src/styles/variables.less
  tailwind.config.js
  yarn.lock
Labels: :white_check_mark: Approved, :sparkles: enhancement

#107 feat: :sparkles: new page for contact us
  craco.config.js
  src/.eslintrc
  src/App.tsx
  src/app.css
  src/app.less
  src/pages/user/contact/index.tsx
  src/styles/fonts.scss
  src/styles/variables.less
  tailwind.config.js
Labels: :white_check_mark: Approved, :sparkles: enhancement

#110 feat::sparkles: navbar according to new design
  src/App.tsx
  src/components/layout/userNav/index.tsx
  tailwind.config.js
Labels: :white_check_mark: Approved, :warning: Changes requested, :sparkles: enhancement

#113 feat(API_integration): :sparkles: configure redux and API integration of contacts
  .vscode/settings.json
  package.json
  src/App.tsx
  src/actions/contacts.action.ts
  src/components/layout/userNav/index.tsx
  src/hooks/useAddDispatch.ts
  src/hooks/useAppSelector.ts
  src/pages/admin/contacts/Contacts.tsx
  src/pages/user/contact/index.tsx
  src/reducers/contacts.reducer.ts
  src/slices/contacts.slice.ts
  src/store.ts
  src/types/global.d.ts
  src/types/interfaces.ts
  src/types/types.ts
  src/utils/api.util.ts
  yarn.lock
Labels: :white_check_mark: Approved

#124 feat: :sparkles: required name field and submit button will be disabled till all required fileds are filled in contact form
  src/pages/user/contact/index.tsx
Labels: :mag: Ready for Review, :sparkles: enhancement

#126 feat(style): :lipstick: responsive navbar and
  .vscode/settings.json
  src/app.less
  src/components/layout/userNav/index.module.less
  src/components/layout/userNav/index.tsx
  src/types/declaration.d.ts
Labels: :mag: Ready for Review, :sparkles: enhancement, :bug: bug

#128 feat(style): :iphone: contact us page responsive
  src/pages/user/contact/index.tsx
Labels: :mag: Ready for Review, :lipstick: styling

#149 feat(auth): :sparkles: connected signup and login with API
  src/.eslintrc
  src/actions/auth.action.ts
  src/pages/user/contact/index.tsx
  src/pages/user/login/index.tsx
  src/pages/user/signup/index.tsx
  src/pages/user/signup/verifyAccountModal/index.tsx
  src/types/interfaces.ts
Labels: :white_check_mark: Approved, :sparkles: enhancement

#157 refactor(style): :recycle: created component for contact us for
  src/App.tsx
  src/components/contactUsForm/index.tsx
  src/pages/user/contact/index.tsx
Labels: :mag: Ready for Review, :recycle: Refactor

#164 feat(style): :lipstick: redesigned hero section
  package.json
  src/.eslintrc
  src/app.less
  src/assets/images/background/floor.webp
  src/assets/images/background/interior.webp
  src/assets/images/background/office.webp
  src/assets/images/background/other.webp
  src/assets/images/background/serviced-apartment.webp
  src/assets/images/background/studio-apartment.webp
  src/assets/images/categories/buyHome.webp
  src/assets/images/categories/commercialProperty.webp
  src/assets/images/categories/listProperty.webp
  src/assets/images/categories/pgRental.webp
  src/assets/images/categories/plot.webp
  src/assets/images/favicon/android-chrome-192x192.png
  src/assets/images/favicon/android-chrome-512x512.png
  src/assets/images/favicon/apple-touch-icon.png
  src/assets/images/favicon/browserconfig.xml
  src/assets/images/favicon/favicon-16x16.png
  src/assets/images/favicon/favicon-32x32.png
  src/assets/images/favicon/favicon.ico
  src/assets/images/favicon/mstile-150x150.png
  src/assets/images/favicon/safari-pinned-tab.svg
  src/assets/images/favicon/site.webmanifest
  src/pages/user/home/hero/hero.scss
  src/pages/user/home/hero/index.module.less
  src/pages/user/home/hero/index.tsx
  src/styles/variables.less
  tailwind.config.js
  yarn.lock
Labels: :white_check_mark: Approved, :sparkles: enhancement

#171 feat(auth): :sparkles: forgot password option
  src/actions/auth.action.ts
  src/components/resetPasswordModal/index.tsx
  src/pages/user/login/components/forgotPasswordModal/index.tsx
  src/pages/user/login/index.tsx
  src/reducers/auth.reducer.ts
  src/slices/auth.slice.ts
  src/store.ts
  src/utils/api.util.ts
Labels: :mag: Ready for Review, :sparkles: enhancement

#176 feat(style): :lipstick: redesign property component
  package.json
  src/App.tsx
  src/components/property/Property.tsx
  src/components/property/index.tsx
  src/hooks/useCurrency.ts
  src/pages/admin/user/User.tsx
  src/pages/user/home/components/hero/index.module.less
  src/pages/user/home/components/hero/index.tsx
  src/pages/user/home/components/listing/index.tsx
  src/pages/user/home/components/listing/listing.scss
  src/pages/user/home/components/properties/index.tsx
  src/pages/user/home/form/Form.tsx
  src/pages/user/home/form/form.scss
  src/pages/user/home/index.tsx
  src/pages/user/home/properties/Properties.tsx
  src/pages/user/home/properties/properties.scss
  src/pages/user/properties/Properties.tsx
  src/pages/user/properties/properties.scss
  src/pages/user/property/Property.tsx
  yarn.lock
Labels: :mag: Ready for Review, :sparkles: enhancement
